### ISSUE TITLE
No dump after running getreport

### ISSUE THREAD

**Issue by matteyeux** [jndok/tools#1]
Hi, there is no new file after running getreport. According to the output everything's fine :( 
I'm running it on Ubuntu 16.04.1.
I also ran it as root. same output.
```
$ ./getreport -u [udid here] -a  
+ Working with device with UDID: [udid here]
+ Dumping to './'!
+ Getting all panic reports from device!
```

**Comment by jndok** [comment]
Works for me. It saves them in the same directory as you run the tool. Also remember that the tool only extracts panic reports, so it doesn't work if you have none on your device.

**Comment by matteyeux** [comment]
Oh okay I thought it would work for every panic in the diagnostic & usage data. 
Thank for your answer
